### ISSUE TITLE
Out of Memory Error

### ISSUE THREAD

**Issue by nschnettler** [BitSyko/LayersManager4.0#19]
After opening overlay Detail Activity. Version 4.2
log:
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 32778252 byte allocation with 5261116 free bytes and 5MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:747)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:568)
at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1014)
at android.content.res.Resources.loadDrawableForCookie(Resources.java:3730)
at android.content.res.Resources.loadDrawable(Resources.java:3603)
at android.content.res.Resources.getDrawable(Resources.java:1852)
at android.content.res.XResources.getDrawable(XResources.java:572)
at android.content.res.Resources.getDrawable(Resources.java:1818)
at android.content.res.XResources.getDrawable(XResources.java:547)
at com.lovejoy777.rroandlayersmanager.OverlayDetailActivity$LoadDrawables.doInBackground(OverlayDetailActivity.java:1111)
at com.lovejoy777.rroandlayersmanager.OverlayDetailActivity$LoadDrawables.doInBackground(OverlayDetailActivity.java:1082)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more

**Comment by andrzejressel** [comment]
Works fine on my overlays.
Which overlay cause this FC?

**Comment by nschnettler** [comment]
On mine too. It´s a crashreport from the PlayStore
