### ISSUE TITLE
Backup when no Overlays installed

### ISSUE THREAD

**Issue by nschnettler** [BitSyko/LayersManager4.0#21]
"im trying to make backup and then app crash"
"Trying to make backup for layers. Typed in back up name, hit OK, then crashed."

App version 4.2

java.lang.NullPointerException: Attempt to get length of null array
at com.lovejoy777.rroandlayersmanager.actions.Restore$1$1.onClick(Restore.java:123)
at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by andrzejressel** [comment]
Looks fine here, maybe it was fixed.

**Comment by nschnettler** [comment]
Fixed somewhere :D
