### ISSUE TITLE
Array out of bounds

### ISSUE THREAD

**Issue by nschnettler** [BitSyko/LayersManager4.0#39]
From Playstore: 

Description: after updating the latest new version the app force close after finishing the intro superuser already granted

Version:  4.3 Beta 2

Logcat: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
at android.util.PathParser$PathDataNode.addCommand(PathParser.java:380)
at android.util.PathParser$PathDataNode.nodesToPath(PathParser.java:260)
at android.graphics.drawable.VectorDrawable$VPath.toPath(VectorDrawable.java:1265)
at android.graphics.drawable.VectorDrawable$VPathRenderer.drawPath(VectorDrawable.java:950)
at android.graphics.drawable.VectorDrawable$VPathRenderer.drawGroupTree(VectorDrawable.java:931)
at android.graphics.drawable.VectorDrawable$VPathRenderer.draw(VectorDrawable.java:938)
at android.graphics.drawable.VectorDrawable$VectorDrawableState.updateCachedBitmap(VectorDrawable.java:705)
at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:280)
at android.widget.ImageView.onDraw(ImageView.java:1187)
at android.view.View.draw(View.java:16209)
at android.view.View.updateDisplayListIfDirty(View.java:15132)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.draw(View.java:16212)
at android.widget.FrameLayout.draw(FrameLayout.java:592)
at android.view.View.updateDisplayListIfDirty(View.java:15132)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.support.v7.widget.RecyclerView.drawChild(RecyclerView.java:3558)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.draw(View.java:16212)
at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3037)
at android.view.View.updateDisplayListIfDirty(View.java:15132)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.draw(View.java:16212)
at android.view.View.updateDisplayListIfDirty(View.java:15132)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.support.design.widget.CoordinatorLayout.drawChild(CoordinatorLayout.java:1049)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.draw(View.java:16212)
at android.view.View.updateDisplayListIfDirty(View.java:15132)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.updateDisplayListIfDirty(View.java:15127)
at android.view.View.getDisplayList(View.java:15155)
at android.view.View.draw(View.java:15930)
at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
at android.view.View.draw(View.java:16212)
at android.widget.FrameLayout.draw(FrameLayout.java:592)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2932)
at android.view.View.updateDisplayListIfDirty(View.java:15132)
at android.view.View.getDisplayList(View.java:15155)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2779)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2611)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1216)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6678)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
at android.view.Choreographer.doCallbacks(Choreographer.java:590)
at android.view.Choreographer.doFrame(Choreographer.java:560)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:5974)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)

**Comment by andrzejressel** [comment]
There is nothing about our app in stacktrace and he's using Xposed - tell him to turn off Xposed and record this FC.

**Comment by andrzejressel** [comment]
Another one:
https://www.dropbox.com/s/3y8d6ifzu81ta0h/2015-08-21-15-41-56.txt?dl=0
